### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ujuc** [ssut/pocketnpm#7]
많이 갔는데 해당 부분에서 에러가 났네요...

```
[428919]  INFO Mirrored: testing-npm-module-seed files=3 sameRev=true worker=2
[428919]  INFO Mirroring: testing123 worker=28
[428919]  INFO Mirrored: testing-publish files=2 sameRev=true worker=28
[428919]  INFO Mirroring: testing1234 worker=21
[428919]  INFO Mirrored: testing-testing files=1 sameRev=true worker=21
[428920]  INFO Mirroring: testing222 worker=14
[428920]  INFO Mirrored: testing001 files=1 sameRev=true worker=14
[428920]  INFO Mirroring: testing233 worker=2
[428920]  INFO Mirrored: testing1029 files=1 sameRev=true worker=2
[428920]  INFO Mirroring: testing234 worker=14
[428920]  INFO Mirrored: testing222 files=0 sameRev=true worker=14
panic: runtime error: index out of range

goroutine 42 [running]:
github.com/ssut/pocketnpm/npm.getLocalPath(0xc42000cb60, 0x1c, 0x0, 0x0, 0xc5cbdb5980, 0xc58cc8aea5)
	/home/ujuc/repos/go/src/github.com/ssut/pocketnpm/npm/utils.go:30 +0x206
github.com/ssut/pocketnpm/npm.(*NPMClient).Download(0xc4200595f0, 0xc5cbdb5980, 0xc565a20c20, 0x7, 0x0)
	/home/ujuc/repos/go/src/github.com/ssut/pocketnpm/npm/npm.go:178 +0x6f
github.com/ssut/pocketnpm/npm.(*MirrorWorker).Start.func1(0xc4201bd200)
	/home/ujuc/repos/go/src/github.com/ssut/pocketnpm/npm/worker.go:105 +0x77a
created by github.com/ssut/pocketnpm/npm.(*MirrorWorker).Start
	/home/ujuc/repos/go/src/github.com/ssut/pocketnpm/npm/worker.go:125 +0x3f
```

**Comment by ssut** [comment]
일부 정상적이지 않은 패키지가 포함되어 있음을 확인했고 수정하도록 하겠습니다.

I assume it's because NPM have some weird packages, and will fix this issue by filtering on the dist.

**Comment by ujuc** [comment]
@ssut 죄송하지만 업무에서 사용할 Node.js repo를 만드는 중이라.. 머무 오랜시간을 기다릴 수가 없습니다.
변경하는데 오래걸리는 부분이 아니라면 제가 해도 될련지요?

가능하다면 변경할 부분을 알려주셨으면합니다.

**Comment by ssut** [comment]
@ujuc 아이고, 개인 사정으로 계속 미뤄지네요.
https://github.com/ssut/pocketnpm/blob/master/npm/worker.go#L105
이쪽 부분입니다. ![`testing234`](https://registry.npmjs.org/testing234) 패키지에 dist 정보가 제대로 들어가있지 않는 것을 확인할 수 있는데 이 부분에서 `tarball` 및 `shasum`에 대한 검증 코드를 넣으시면 됩니다.
![image](https://user-images.githubusercontent.com/2366668/31979114-effc4eb6-b97f-11e7-8c4a-2906b08bd3d4.png)
미리 수정해서 쓰셔도 되고, 가능하다면 이번주 내로 업데이트 해보겠습니다.

I'm sorry for the delayed response. You can fix this issue by putting an additional verification code on https://github.com/ssut/pocketnpm/blob/master/npm/worker.go#L105, as the package `testing234` contains an unexpected dist information on both `tarball` and `shasum`. I'll try to fix it as soon as possible (within a week at most).

**Comment by ujuc** [comment]
코드 보다보니...

https://github.com/ssut/pocketnpm/blob/master/npm/utils.go#L29

이줄에서 Path를 가져오는데...
해당 값이 `"/testing-uglify/-/testing-uglify-0.1.0.tgz"` 이런 형태로 들어와서 나눠지기를 `["/" "testing-uglify/" "-/testing-uglify-0.1.0.tgz"]` 요렇게 되네요...

우선 해당 코드를 다음처럼 고쳐서 돌리고 있습니다.... 

```
func getLocalPath(base string, path string) string {
	local := filepath.Join(base, path)
	return local
}
```

`//` 중복이 되더라도 폴더는 제대로 된 곳으로 만들어지고, 문제는 위 testing234 와같이 아래 값이 없는 경우이긴한데... 뭐 저거는 나오는거보고 삭제해야죠 뭐 :) 급한 불은 끈건지 모르겠네요.;

**Comment by ssut** [comment]
코드 업데이트 했으니 확인하시고 다시 시도해보시면 될겁니다. 제보 감사합니다.

Thanks for submitting a bug report! I updated the code to fix this problem, so please check it again.
